name: cron
on:
  schedule:
    - cron: '0 6,10,14 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: cron
  cancel-in-progress: true

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Run Sync
        run: |
          python3 main.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # cname: stonks.jossef.com